"""add discarded_at and discarded_notes to Device

Revision ID: 92e67d3af738
Revises: fff94b0da3b1
Create Date: 2026-02-16 20:06:46.070478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92e67d3af738'
down_revision = 'fff94b0da3b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discarded_at', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('discarded_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_devices', schema=None) as batch_op:
        batch_op.drop_column('discarded_notes')
        batch_op.drop_column('discarded_at')

    # ### end Alembic commands ###
