"""Add inventory models

Revision ID: fff94b0da3b1
Revises: 24869b805f09
Create Date: 2026-02-13 13:06:49.630423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff94b0da3b1'
down_revision = '24869b805f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_number', sa.String(length=50), nullable=False),
    sa.Column('device_type', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('serial_number', sa.String(length=200), nullable=True),
    sa.Column('scope', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_number')
    )
    op.create_table('inventory_person_refs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ldap_username', sa.String(length=150), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_person_refs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_person_refs_ldap_username'), ['ldap_username'], unique=False)

    op.create_table('inventory_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('inventory_handovers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('giver_id', sa.Integer(), nullable=False),
    sa.Column('handover_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('protocol_number', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['inventory_devices.id'], ),
    sa.ForeignKeyConstraint(['giver_id'], ['inventory_person_refs.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['inventory_person_refs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_handovers')
    op.drop_table('inventory_settings')
    with op.batch_alter_table('inventory_person_refs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_person_refs_ldap_username'))

    op.drop_table('inventory_person_refs')
    op.drop_table('inventory_devices')
    # ### end Alembic commands ###
